# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Content' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Content

pod 'SnapKit', '~> 4.0.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'Alamofire', '~> 4.7.2'
pod 'SwiftyJSON', '~> 4.1.0'
pod 'MJRefresh', '~> 3.1.15.3'
#pod 'SDWebImage', '~> 4.4.0'
pod 'Kingfisher', '~> 4.8.0'
pod 'RealmSwift', '~> 3.6.0'
pod 'SDCycleScrollView', '~> 1.75'


pod 'UMCCommon'
pod 'UMCSecurityPlugins'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'

# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'

# 集成微信(完整版14.4M)
pod 'UMCShare/Social/WeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMCShare/Social/ReducedQQ'

# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMCShare/Social/QQ'





end
