# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Content' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Content

pod 'SnapKit', '~> 4.0.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'Alamofire', '~> 4.7.2'
pod 'SwiftyJSON', '~> 4.1.0'



end
